### ISSUE TITLE
If I search the help section or open sitemap it goes blank

### ISSUE THREAD

**Issue by msellmer** [cwrc/CWRC-Writer#109]
If I search the help section it goes blank. The last menu item in help, "Sitemap" is also blank and I lose the menu.

![screen shot 2013-10-16 at 8 50 52 am](https://f.cloud.github.com/assets/1838266/1343998/d88359a0-367a-11e3-8189-2ae1efdc5af3.png)

**Comment by ilovan** [comment]
no longer relevant to the way "Help" is handled now.
