### ISSUE TITLE
Upgrade to TinyMCE 4

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-Writer#122]

**Comment by ilovan** [comment]
Based on your email, did this happen recently, @jchartrand ? If yes, can we close this?

**Comment by ajmacdonald** [comment]
No, this hasn't happened yet.

**Comment by ilovan** [comment]
Further details of the TinyMCE 4 update risks and benefits should be discussed in further detail in order tho asses the place of this issue in the priorities list

**Comment by SusanBrown** [comment]
Should we revive this discussion @jchartrand or has this been done?

**Comment by ajmacdonald** [comment]
Done.
https://github.com/cwrc/CWRC-Writer/commit/4a3e87647a487c6c8618face3ee454ab77fcb3ae
