### ISSUE TITLE
Entity 'tagging' should always insert (even in overlap mode) an XML tag unless overlap prevents it. 

### ISSUE THREAD

**Issue by jchartrand** [cwrc/CWRC-Writer#126]
Even when in overlap mode still try to insert the xml tag for an entity along with the rdf.  If the xml can't be added because of introduced overlap, then warn the user.

Susan to draft message to show user.

**Comment by ajmacdonald** [comment]
Do we really want a warning message to appear every time an overlapping entity is added (while already in overlap mode)?

**Comment by ilovan** [comment]
desired behaviour reached
