### ISSUE TITLE
When a title is tagged, the stylesheet needs to reflect the styling options for the XML tag that has been inserted.

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#130]
Not sure if this is an editor issue or a problem with the CSS.
Inserting an analytic title in the sample writing document does not produce the quotations marks around the title that the stylesheet should be dictating. Maybe this is because title isn't fully implement yet, in which case ignore and double check when the implementation is complete: just wanted to flag it.

**Comment by ajmacdonald** [comment]
Seems to be fixed.
