### ISSUE TITLE
Role, certainty, etc. pop-up needs to resize to fit the current browser window.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#211]
![screen shot 2014-07-22 at 3 44 53 pm](https://cloud.githubusercontent.com/assets/6600070/3665803/a53b7046-11e9-11e4-945c-aebae7584055.png)

**Comment by ilovan** [comment]
After the update to Tiny MCE the size of the attribute window is no longer scaling to the size of the screen, or scrollable.

**Comment by ajmacdonald** [comment]
Should be fixed.

**Comment by ilovan** [comment]
confirmed
