### ISSUE TITLE
Note placeholder is messing the format of the text in both Chrome and Firefox

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#219]
![screen shot 2014-07-31 at 3 10 01 pm](https://cloud.githubusercontent.com/assets/6600070/3771646/361d0b1a-18f7-11e4-9c8b-912c5548a24b.png)

**Comment by ilovan** [comment]
Andrew, is there any way we could have the content of the research note made visible only when the user click on a placeholder symbol, either through a pop-up or directly in the text area? Ideally one click on the placeholder to show the text of the research note and another to hide it. If the answer is yes, how  long would it take to set up?

**Comment by ilovan** [comment]
I should have probably pose the question in the thread for #245

**Comment by ajmacdonald** [comment]
It currently works in the way you're describing, i.e. you have to click the note icon in order to see the note content.
