### ISSUE TITLE
CWRC Writer - Islandora authentification issue

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#242]
From @mpm1 's email:

"By the looks of this, I think this may caused by miscommunication of where the user provides their login credentials.

Using the function cD.initializeWithCookieData(null) assumes that some other service has authenticated the user and created the required cookies. This would be the case if the writer is embedded into islandora and can only use the write after they have logged in.

The function cD.initializeWithLogin(username, password) allows you to pass in the username and password. This would allow the system to initialize based on some sort of example user account or pass in information provided somewhere else on the page.

I recommended to Andrew to use the cD.initializeWithCookieData(null) function because at the time I assumed that the user would have already logged in through Islandora. I think in the case of the demo pages it may be best to create some sort of demo user and call the function cD.initializeWithLogin using that users login information or have some sort of login page."

This is a high priority bug to be fixed, if possible, before the Hamilton College demo on Friday.

**Comment by SusanBrown** [comment]
@ilovan is this fixed now?

**Comment by jefferya** [comment]
If the CWRC-Writer is opened from the same server hosting the CWRC entities
and the user is actively logged into the CWRC repository in the same
browser then yes.

If the aim is to allow the standalone version of CWRC-Writer (unassociated
with CWRC-Repository, living on a different server but still able to create
CWRC entities) then this would need a mechanism to enter user credentials
like the NERVE tool.
