### ISSUE TITLE
Both TEST and DEV: Overlap mode broken

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#244]
Setting in the setting panel doesn't switch to overlap when tagging an overlapping entity.

![image](https://cloud.githubusercontent.com/assets/6600070/4529798/519296b4-4d7a-11e4-89db-97bd1217ea57.png)

**Comment by ilovan** [comment]
## Current status: ##

#### 1. no overlap -> overlap ####
  a. From the settings panel: **no popup** (should display: *The editor mode will be switched to XML and RDF (Overlapping Entities) and only RDF will be created for the entities you intend to annotate. Do you wish to continue?*)

**Possible bug:** If a document is saved in the overlap mode without any actual overlapping entities being created, when the save document is being reloaded, it defaults back to the "no overlap" mode. Is this the desired behaviour, @susanirenebrown ?

  b. When trying to create an overlapping entity - **OK**
#### 2. no overlap -> xml only
  a. From the settings panel only: **no popup** (should display: *If you select the XML only mode, no RDF will be created when tagging entities. Furthermore, the existing RDF annotations will be discarded. Do you wish to continue?*)
#### 3. overlap -> no overlap ####
  a. From the settings panel only: **OK** 
#### 4. overlap -> xml only ####
  a. From the settings panel only: **OK** 
#### 5. xml only -> overlap ####
  a. When trying to tag an overlapping entity: this is a bit tricky and I don't think we ever talked about the desired behaviour, @SusanBrown. I suggest a message that says: *This operation is not allowed in an XML structure; only an RDF annotation could be added at this location, but the editor more would have to be changed to XML and RDF (overlapping entities). Do you wish to proceed with the change?Yes-no*
 
 b. From the settings panel only: **no popup** (should display: *The editor mode will be switched to XML and RDF (Overlapping Entities) and only RDF will be created for overlapping entities. Do you wish to continue?*)
#### 6. xml only -> no overlap ####
From the settings panel only: **no popup** (should display: *XML tags and RDF/Semantic Web annotations equivalent to the XML tags will be created, consistent with the hierarchy of the XML schema, so annotations will not be allowed to overlap. Do you wish to continue? Yes-No*)

**Comment by SusanBrown** [comment]
> On Jan 20, 2015, at 5:48 PM, Mihaela Ilovan <notifications@github.com> wrote:
> 
> Current status:
> 
> 1. no overlap -> overlap
> 
> a. From the settings panel: no popup (should display: The editor mode will be switched to XML and RDF (Overlapping Entities) and only RDF will be created for the entities you intend to annotate. Do you wish to continue?)
> 
> Possible bug: If a document is saved in the overlap mode without any actual overlapping entities being created, when the save document is being reloaded, it defaults back to the "no overlap" mode. Is this the desired behaviour, @susanirenebrown <https://github.com/susanirenebrown> ?
> 
> 
No, I think that it should be saved in overlap mode.
> b. When trying to create an overlapping entity - OK
> 
> 2. no overlap -> xml only
> 
> a. From the settings panel only: no popup (should display: If you select the XML only mode, no RDF will be created when tagging entities. Furthermore, the existing RDF annotations will be discarded. Do you wish to continue?)
> 
> 3. overlap -> no overlap
> 
> a. From the settings panel only: OK
> 
> 4. overlap -> xml only
> 
> a. From the settings panel only: OK
> 
> 5. xml only -> overlap
> 
> a. When trying to tag an overlapping entity: this is a bit tricky and I don't think we ever talked about the desired behaviour, @SusanBrown <https://github.com/SusanBrown>. I suggest a message that says: This operation is not allowed in an XML structure; only an RDF annotation could be added at this location, but the editor more would have to be changed to XML and RDF (overlapping entities). Do you wish to proceed with the change?Yes-no
> 
> 
This sounds good. Typo: “more” for “mode”

**Comment by ajmacdonald** [comment]
I've added the confirmation dialog for 6. The other confirmation dialogs were already in place, so if you're not seeing them then something is wrong.

**Comment by ilovan** [comment]
All popups are in place now, thanks.
