### ISSUE TITLE
Both TEST and DEV: Note placeholder not displaying properly in neither  Firefox nor Chrome

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#245]
Interestingly enough, the placeholders of older notes (i.e. that came with the template) are displaying nicely - see below, the Chrome screenshot.

Chrome:
![image](https://cloud.githubusercontent.com/assets/6600070/4533526/ec633212-4d9c-11e4-9043-a3f43e5cd8eb.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/6600070/4533540/fb54017a-4d9c-11e4-9ca8-ef8d696e9d50.png)

**Comment by SusanBrown** [comment]
So, @ilovan, since this is waiting on us to decide, could you please sketch out a couple of interface options, or just summarize the choices verbally, and see if Geoffrey and you and I can decide this via email? If you think we clearly need a meeting, let's set one up.
