### ISSUE TITLE
CWRC ENTRY documents: no css

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#282]
Is there anything I need to do to the stylesheets to make them readable by the CWRC Writer?

CEWW new entry css: http://cwrc.ca/templates/css/ceww.css
CWRC entry: http://cwrc.ca/templates/css/cwrc.css

**Comment by ajmacdonald** [comment]
They need to be manually converted to the CWRC Writer format. I'll do that.
