### ISSUE TITLE
Orlando: when tags are visible, Ps inside SHORTPROSE invisible 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#283]
![image](https://cloud.githubusercontent.com/assets/6600070/5828658/06a9eaa6-a0c4-11e4-8794-5ca3b8a481e7.png)

**Comment by ilovan** [comment]
same as #261 , closed by @ajmacdonald on Dec 12.

**Comment by ajmacdonald** [comment]
They're visible for me. Can you provide more details?

**Comment by ilovan** [comment]
sorry - my bad - this issue occurs in TEST, but not in DEV
