### ISSUE TITLE
Overlap mode defaulting back to no overlap if no overlapping entities are added.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#286]
If a document is saved in the overlap mode without any actual overlapping entities being created, when the save document is being reloaded, it defaults back to the "no overlap".

See discussion in #244

**Comment by ajmacdonald** [comment]
Should be fixed. NB: this will only apply to newly saved documents since I had to alter the save format slightly.

**Comment by ilovan** [comment]
I just saved a sample poem as document "testjantwentynine" in overlap mode, but when I reopen it - it reopens as a no overlap document. (tried it in both Firefox and Chrome, if that makes any difference, with both sample and template documents)

**Comment by ajmacdonald** [comment]
Should be fixed now, please test.

**Comment by ilovan** [comment]
It's fixed, thanks.
