### ISSUE TITLE
Dialogs: "edit" & "select" buttons should not be clickable unless an item is selected in the search result listing

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#290]
same as cwrc/CWRC-Dialogs#59

**Comment by jchartrand** [comment]
Hi Mihaela:

This seems more like it requires a change to the Dialog code, rather than a change to the CWRCWriter code?

james

**Comment by ilovan** [comment]
It seemed to me as well, but I believe he has some agency on their behaviour when he integrates the dialogs. 
It's up to you to decide whether you want it in the CWRC Writer repository to keep track of desired Dialogs behaviour or not.

**Comment by jchartrand** [comment]
Just to clarify, I suggested moving issues that are specific to CWRCWriter to the CWRCWriter repo, not, however, moving issues that are specific to the Dialogs to the CWRCWriter repo.  And, I suggested that for issues that have some CWRCWriter part, we should extract that part, and create a new issue for *just that part* in the CWRCWriter repo.  All towards keeping separate things separate.

In this case, however, the entire change seems like one that should be made only to the dialogs (and not to the CWRCWriter) for at least two reasons:

- you’d likely want the same behaviour in the dialogs anywhere they are used, including by apps other than the CWRCWriter, and not just when they are used in the CWRCWriter
- anything within the dialogs should be kept self contained, if it can, to more easily allow substituting new dialog code later.

A further question:  if the changes are to be made to the dialog code (not the CWRCWriter code), should Andrew be making those changes?  Although, he is a JS wizard (imo), it will still take time to familiarize himself with that code.

**Comment by ilovan** [comment]
Hi James, I consulted with Jeff and Susan, and we would, indeed, like Andrew to try to fix this issue in the Dialogue code. 
Thanks.

**Comment by ajmacdonald** [comment]
Should be fixed.

**Comment by ilovan** [comment]
Works now, thanks. Can you send a pull request to Jeff for the standalone version of the Dialogs? We want to keep them in synch as much as possible.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-Dialogs/pull/68
