### ISSUE TITLE
Add licensing information to the CWRC Writer repository 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#294]
Hi @jchartrand, it has been brought to our attention by a research group who intents to test the use of CWRC Writer in their environment that we currently don't have any licensing associated with the CWRC Writer repository. 

From what Susan remembers, the intention at some point in the past was to add the GNU Public licence to all the CWRC repositories. Do you have any thoughts on this matter? Is there another Open Source licence you would recommend?

If not, the instructions to ad the licence are here: http://choosealicense.com/licenses/gpl-2.0/

I'll add this issue to the top of the priorities list for Andrew this week.

**Comment by jchartrand** [comment]
Hi Mihaela,

My vague memory is that Susan (or someone at Alberta) was going to ask the the U of A intellectual property people which licence should be used, and what boilerplate (as described in the link you provided below) should be included.

james

**Comment by jchartrand** [comment]
Let’s take this off the priority list until the licence has been fully worked out, and you can give us the exact text you’d like inserted verbatim.  I don’t want to run the risk that Andrew or I misinterpret the legalese.

**Comment by ilovan** [comment]
Hi James, I discussed this with Susan today and we are going with the GNU GPL v2.0. The GitHub issue stays in the priority list at its current location. I believe there are instructions on how to properly apply the licence at the URL I sent you. 

Thanks,
Mihaela

**Comment by jchartrand** [comment]
Hi Mihaela, Susan:

I again have to insist that neither Andrew nor I should interpret the instructions to ‘properly apply' the licence, which, for example, asks for some extra information down in the 

'How to Apply These Terms to Your New Programs’  section of the link you sent.

The code belongs to the University of Alberta, not Open Sky, and I really don’t want us making a mistake with the licence.   

So, again, if you can give us the exact text to paste in, we can easily do that.

james

**Comment by ilovan** [comment]
I understand your concerns, James.

@SusanBrown , do you agree with the following description, copyright notice and contact info for the boilerplate (see in bold):

**CWRC Writer. Browser-based XML editor**
    Copyright (C) **2015  Canadian Writing Research Collaboratory**

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

**Contact: 
cwrc@ualberta.ca
Canadian Writing Research Collaboratory
University of Alberta
4-20 Humanities Centre
Edmonton, AB
Canada T6G 2E5**

**Comment by susanirenebrown** [comment]
This is fine.

James, if you would prefer that Mihaela or I put the licence in, that would be fine.

cheers,
Susan


On March 6, 2015 at 2:39:40 PM, Mihaela Ilovan (notifications@github.com) wrote:
I understand your concerns, James.

@SusanBrown , do you agree with the following description, copyright notice and contact info for the boilerplate (see in bold):

CWRC Writer. Browser-based XML editor
Copyright (C) 2015 Canadian Writing Research Collaboratory

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Contact:
cwrc@ualberta.ca
Canadian Writing Research Collaboratory
University of Alberta
4-20 Humanities Centre
Edmonton, AB
Canada T6G 2E5

**Comment by jchartrand** [comment]
> On Mar 6, 2015, at 5:01 PM, Susan Brown <notifications@github.com> wrote:
> 
> This is fine.
> 
> James, if you would prefer that Mihaela or I put the licence in, that would be fine.

That would be great.  Thank you both for your understanding.

james

> 
> cheers,
> Susan
> 
>

**Comment by ilovan** [comment]
Added the license file in dev and master. Since the boiler plate at the top of each file is just a recommendation and because we don't have it in any other CWRC repository, we decided to leave it out for now and see if this acceptable for licensing purposes for the people who want to use CWRC Writer.
