### ISSUE TITLE
Top of the cascading rightclick  menu is cut off (search box, first tags - "hidden")

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#296]
![screen shot 2015-03-16 at 1 16 48 pm](https://cloud.githubusercontent.com/assets/6600070/6674872/464b74c4-cbe2-11e4-9794-05bae1dca4ae.png)

**Comment by ajmacdonald** [comment]
This behaviour seems like it might be browser specific. @ilovan can you please provide the browser you're using, along with the size of the browser window in pixels?

**Comment by ilovan** [comment]
It happens in both Firefox and Chrome when:
* the lists of tags available for insertion inside, before or after is sufficiently long (eg the second paragraph of the letter sample)
* the selected tag is high enough in the structure panel
* the height of the browser window is small enough so that the cascading drop down with the allowed tags is cascading up instead of down 

I hope this makes sense. Can you reproduce it now? I managed to reproduce the issue in both Firefox and Chrome today.

**Comment by ajmacdonald** [comment]
Yes I can reproduce it. Thank you for the info.
