### ISSUE TITLE
Embeded Dialogs: Country not dispalying.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#297]
![screen shot 2015-03-16 at 1 47 55 pm](https://cloud.githubusercontent.com/assets/6600070/6674976/16182b5c-cbe3-11e4-860b-7ba9ddaf9940.png)

Standalone dialogs:
![screen shot 2015-03-16 at 1 49 16 pm](https://cloud.githubusercontent.com/assets/6600070/6675004/5270fbce-cbe3-11e4-9473-2a3e1a9e66c7.png)

**Comment by ajmacdonald** [comment]
Where are you testing the standalone version?
When I try it here ( http://apps.testing.cwrc.ca/ccm-interface/CWRC-Dialogs/ ) I get this:
![stockho](https://cloud.githubusercontent.com/assets/882444/6875754/daa2f15c-d497-11e4-9dd9-c8fb0b6ee740.png)

**Comment by ilovan** [comment]
At http://cwrc-dev-01.srv.ualberta.ca/dev/CWRC-Dialogs/ (the site Jeff set up for his version of the dialogs). The one you mentioned was used by ARC and is now obsolete. Sorry about that.

**Comment by SusanBrown** [comment]
Is there any reason we can’t disable the obsolete site, Mihaela?

**Comment by ilovan** [comment]
no reason, it just got killed off by @jefferya , to avoid any further confusion.

**Comment by susanirenebrown** [comment]
great
happy weekend, everyone ;)

**Comment by ajmacdonald** [comment]
CWRC-Writer is using this URL: http://apps.testing.cwrc.ca/cwrc-mtp/geonames/
The standalone dialogs are using this URL: http://cwrc-dev-01.srv.ualberta.ca/cwrc-mtp/geonames/

The response from http://apps.testing.cwrc.ca/cwrc-mtp/geonames/ has empty <countryName> tags, hence why the country isn't displaying.
@jefferya this seems like a backend issue to me, but let me know if there are changes on my side to make.

**Comment by jefferya** [comment]
Hi Andrew,

No changes required on your end at this time.

"apps.testing" uses a newer version of the code base. The bug causing the
issue has been fixed, I think.

"cwrc-dev-01" uses a older version of the code base before the bug was
introduced.

At some point, the differences between the two locations need to be
reconciled (code and database contents).

Cheers,
~Jeff

**Comment by brundin** [comment]
JCA and MRB modified the code base on cwrc-dev-01 to resolve the problem, and the country name is now displaying.
