### ISSUE TITLE
CWRC entry: Annotate person entity on a Birthname tag

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#303]
* On 2015-03-25, at 3:12 PM, Andrew MacDonald wrote:

Hi Susan,

Apologies for not addressing this sooner.

I'm not sure if I'm duplicating your initial issue, because the image you attached is unavailable. I tried to tag the contents of BIRTHNAME by clicking the tag in the markup panel twice, then attempting to add a tag. This resulted in the overlapping message. In this particular case, it's happening because the text selection starts in "{Given name of writer at birth}" and ends in "{Last name of writer at birth ". (See attached image)

![selection_issue](https://cloud.githubusercontent.com/assets/6600070/6863204/76fdc7e2-d412-11e4-89e1-63a4e8686579.PNG)

Whether or not a tag is mapped to an annotation shouldn't affect your ability to add the tag. If you can provide me with directions of what you're trying (i.e. which tags work and which don't, and how you're trying to tag them), I'll see if I can get to the bottom of the issue.

For the overlapping mode RDF is created for all entities/annotations. If the entity doesn't overlap with other tags, then additionally, an XML tag is created for it.

Andrew

* On Friday, March 20, 2015 11:13 AM, Susan Brown <sibrown@ualberta.ca> wrote:

Hi James and Andrew,

I’m working with http://apps.testing.cwrc.ca/editor/dev/editor_dev.htm#templates/ceww_new_entry_template

I’m trying to apply a name annotation to the tagged name in CEWW template. The only way I can apply the tag without getting the overlapping entities message is by selecting just “Hume” within the surname tag. When I click on birthname in the markup panel to select it, I get the overlap error. But if birthname is indeed selected, there should be no overlap error. Can you elucidate what is going on? It seems to be much more restrictive than I would have anticipated.

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/6600070/6863136/9b143dc4-d411-11e4-9a03-721f768f9ab2.jpg)

Is it, as I suspect, that birth name isn’t mapped to the annotation structure? I have no trouble applying annotations to things in name tags. 

Also, can I clarify what is happening in overlap mode: are XML tags being created if but only if they don’t overlap, or are no XML tags being created at all?

cheers,
Susan

**Comment by ilovan** [comment]
Annotation mappings for the CWRC entry schema: https://docs.google.com/a/ualberta.ca/document/d/11WBJMToqzuwrDPa1XZ9l80Wo1uNERALGHM1Lxwy16mw/edit

**Comment by ilovan** [comment]
I believe this is related to #301

**Comment by SusanBrown** [comment]
It's not exactly the same as #301. That has to do with duplicating tags. This has to do with the way that entities get selected/inserted. I think much of the problem has been dealt with by the schema modification. Am going to close it for now.
