### ISSUE TITLE
multiplication of reg attribute in the popup for the birthname tag

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#304]
working with http://apps.testing.cwrc.ca/editor/dev/editor_dev.htm#templates/ceww_new_entry_template

Can't seem to paste image into github for some reason, but it was pasted into an email sent on March 27th around 11:15pm.

**Comment by ajmacdonald** [comment]
Relevant schema part: https://github.com/cwrc/CWRC-Schema/blob/master/schemas/cwrc_entry.rng#L4087

**Comment by ajmacdonald** [comment]
I've added a check for duplicates which solves the problem, however it could be worthwhile (though more time consuming) to examine the code to see why REG is being included so many times in the first place.
