### ISSUE TITLE
Really weird screen bug after creating an entity

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#313]
Wonder if this has to do with the date picker in the entity creation dialogues. I didn't use them but I did try to add dates when trying unsuccessfully to create a more complex entity. Also chose role: Correspondent in the dialog after creating the entity. Have not been able to reproduce so just let this sit as a possible indication of a problem.

Screen was frozen; couldn't scroll; had to reload (and so lost my edits in CWRC-Writer).

![image](https://cloud.githubusercontent.com/assets/545952/7262570/cfe7964a-e848-11e4-98af-1338e7a2bead.png)

**Comment by jefferya** [comment]
could be related to #314
