### ISSUE TITLE
Entity dialogue integration: unable to add date (e.g. person birth date)

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Writer#314]
The integrated entity dialogues produce an error when trying to add a date to the entity (e.g. when creating a new person entity and trying to add a birth date).

The following javascript error is produced:

Uncaught Error: Browser doesn't support addEventListener or attachEvent

Note: the stand-alone dialogues (i.e. before integrated into the CWRC-Writer) do not produce this error.  Could there be a conflict between the CWRC-Writer and CWRC-Dialogues?

**Comment by jefferya** [comment]
commenting out the " ko.utils.registerEventHandler" for "changeDate" appears to prevent the javascript error but also disables the datepicker popup - not ideal but is a quick kludge for a demo and testing.

**Comment by ajmacdonald** [comment]
I think this is being caused by this bug: https://github.com/knockout/knockout/issues/1764
The reason the standalone dialogues don't experience the error is because they're not using requirejs to load the js files.
