### ISSUE TITLE
add setRepositoryBaseObjectURL to the initial config

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Writer#325]
setRepositoryBaseObjectURL - is the base for the entity URIs (i.e commons.cwrc.ca). Can it be set with the other config parameters (such as cwrcApiUrl) instead of within a separate section of dialogManager?

Reference:
https://github.com/jefferya/CWRC-Writer/blob/db8da223024bda686bf2d5130c1fb6629aab24f9/src/js/dialogManager.js#L67

**Comment by SusanBrown** [comment]
@jchartrand  or @ajmacdonald Please respond

**Comment by ajmacdonald** [comment]
I'm currently working on the TinyMCE upgrade. This can and will be implemented afterwards.
