### ISSUE TITLE
Orlando biography and writing documents: URIs

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Writer#326]
When a name is tagged within an Orlando biography or writing document, the URI of the selected/edited/created entity is not added as an attribute to the XML name tag.  Also applies to organizations, places, and titles elements used with Orlando schemas. 

TEI docs seem ok.

**Comment by ilovan** [comment]
CWRC entry documents are working OK, with the REF attribute containing the URI. 

@ajmacdonald , can you please confirm what document you used to map the Orlando tags and attributes to entities? Was it https://docs.google.com/document/d/1PGfJBXhURbpeBuaORwlggRbxKcruVloJ_GN8creAz3k/edit?
If so, @brundin , can you please revise to include the use of the REF attribute to record the URI of the entities referenced?

**Comment by ajmacdonald** [comment]
@ilovan Yes it was.

**Comment by brundin** [comment]
Added the @REF attribute to the Google Doc CWRC and Orlando annotation object form documentation for person, organization, place, and title objects.  So, in the document "Annotation object forms -- CWRC entry elements and attributes" (https://docs.google.com/document/d/11WBJMToqzuwrDPa1XZ9l80Wo1uNERALGHM1Lxwy16mw/edit), and the document "Annotation object forms -- Orlando elements and attributes" (https://docs.google.com/document/d/1PGfJBXhURbpeBuaORwlggRbxKcruVloJ_GN8creAz3k/edit), in the person, organization, place, and title sections, they now have the @REF attribute documented.  The "Annotation object forms -- TEI elements and attributes" document (https://docs.google.com/document/d/1swmwJdgqxyMmd6YIhq6nPuKA7Na5EadYG6xVk4ua3MY/edit) already had the @ref attribute documented.

Andrew (@ajmacdonald): as you did with the TEI CWRC-Writer template dialogs, you can add the functionality for the CWRC entry and Orlando template dialogs for person, organization, place, and title the ability to save the URI of the body or source entity in the REF attribute.  Thanks!
