### ISSUE TITLE
Editor mode: the way in which the mode info is stored with the object or managed should be reviewed

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#333]
All versions.

As things stand now, in the Islandora integrated version, as well as in the stand-alone version, when the user uploads/replaces the source file with an XML document that doesn't have any rdf annotations, the editor mode defaults to xml only even though no user choice was involved. 

To some extent we've run into similar issues with #195 and #134

**Comment by ilovan** [comment]
related to #329

**Comment by ajmacdonald** [comment]
I've set the default mode to XML & RDF no overlap.
However, this can be overridden by a cw:mode setting in the RDF:
```
<rdf:Description rdf:about="http://localhost:8080/editor/documents/null">
	<cw:mode>0</cw:mode>
</rdf:Description>
```
0 = XML & RDF
1 = XML
2 = RDF

**Comment by susanirenebrown** [comment]
Thanks. 

Should Mihaela be scooping up this kind of thing towards documentation or are you documenting it somewhere?

**Comment by jchartrand** [comment]
> On Jul 22, 2015, at 4:06 PM, Susan Brown <notifications@github.com> wrote:
> 
> Thanks. 
> 
> Should Mihaela be scooping up this kind of thing towards documentation or are you documenting it somewhere?
> 
IMO, this, and many other things, should go into more formalized documentation that we maintain as we go.  We should have a user manual, an administrative manual, and a programmers manual.  This particular point seems best in the administrative manual, with a pointer to it from both the user and programmers' manuals.  I’m happy to volunteer to get the documentation going (I like writing up this kind of thing) if that makes sense.
>

**Comment by SusanBrown** [comment]
That would be great if you could start the administrative manual. Just get it going though--don't lavish a ton of time on it--because I hope we can apply for another grant that would be specifically about  making CWRC-Writer more usable by others in other frameworks than CWRC and that would include documenting it. More on this when Mihaela is back from holidays.

**Comment by SusanBrown** [comment]
@jchartrand If you have incorporated this into the administrative manual, please close this ticket.

**Comment by jchartrand** [comment]
I think you’d already closed it, coincidentally almost exactly one year ago.
