### ISSUE TITLE
Remove "Add schema" button from the Settings panel

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#334]

**Comment by ilovan** [comment]
This portion of the settings panel should not be available for the integrated version of CWRC-Writer. Could it be set up so that it is easy for dgi to turn it off?

**Comment by ilovan** [comment]
![screen shot 2015-08-24 at 2 38 43 pm](https://cloud.githubusercontent.com/assets/6600070/9451773/de5b3ede-4a6d-11e5-801e-2fd62cffdcab.png)

**Comment by ajmacdonald** [comment]
After the CWRC-Writer has been initialized, call ```writer.settings.hideAdvanced();``` to turn it off.
