### ISSUE TITLE
Read-only version: Remove warning notification when trying to close the URL

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#337]
Question: for the annotation-only version, do the annotations get automatically saved, or does the user have to save them? If the former, remove the warning notification from there as well.

**Comment by ajmacdonald** [comment]
There is no auto-save at the moment.

**Comment by SusanBrown** [comment]
So then if someone is leaving the annotator they shoudl get the warning still.

**Comment by ilovan** [comment]
Status as of August 24: warning notification removed from read-only version but also missing from the annotation-only version.
