### ISSUE TITLE
Read-only and annotation versions: keep the structure panel available, but collapsed (or deselected for the annotation version) by default 

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#338]
This would allow people to click on different tags in order to automatically scroll to that section of the document - a nice feature for longer documents.
	
Alternatively, and perhaps even better for a reading environment, instead of the regular structure panel, display a modified one that would contain the headers only (with their content, not just the header label), hierarchically organized by label and clickable to allow readers to move to that point in the document. In a schema that doesn’t have <HEADER> tags, default to the tag structure panel.

**Comment by ajmacdonald** [comment]
The first part of this is done.
The alternative part is possible but would be more involved. What are the list of tags that you'd want to filter the structure panel by?

**Comment by SusanBrown** [comment]
I think all we'd want to do is use the left panel to expose the contents (not the tag names) of the HEADING and HEAD tags so that the user could click on them to navigate to that point in the document.

**Comment by ilovan** [comment]
Great work, Andrew, but would it be possible to change the heading of the "Markup" panel to "Structure" or "outline" for the annotation and read-only versions?
Also, I noticed that below the div 0 level, all headings are nested on the same level, while some of them are headings of div 1 and others are headings of div 2 (e.g. Family - div 1; grandfather  - div 2 ; in the panel, grandfather should be indented under Family).

I'm going to reopen this - please let me know if you want me to create separate issues.

**Comment by ajmacdonald** [comment]
Those 2 issues should be addressed now.

**Comment by ilovan** [comment]
Hi Andrew, I tested the heading nesting and we seem to have a problem with the CWRC schema:
Please see the "published texts" section in the CEWW template: http://apps.testing.cwrc.ca/editor/dev/reader.htm#templates/ceww_new_entry_template
Also, I am not sure why the last header in the TEI prose is followed by ellipsis in the structure panel: http://apps.testing.cwrc.ca/editor/dev/reader.htm#templates/prose

**Comment by ajmacdonald** [comment]
I'll look into what's going on with the CEWW template.

There is an ellipsis because the the title is being truncated when it's too long. In this case the length is extra whitespace so I'll look into filtering that out.

**Comment by ajmacdonald** [comment]
Should be fixed now.

**Comment by ilovan** [comment]
Just checked:

No more ellipsis in the TEI prose.
CEWW template: Published works is a level 2 heading while fiction, non-fiction, etc. are level 3. Despite that, they are listed at the same level now.

**Comment by ajmacdonald** [comment]
Are headings always guaranteed to have subtypes/levels? Currently I'm sorting based on how nested they are in the document.

**Comment by ilovan** [comment]
In the CWRC schema "level" is a required attribute for HEADING, but not in the other schemas we support (Orlando, TEI).

Could we set it up as follows:

if heading has level attribute, order and indent by that
If heading has no attribute, order and indent by the type of the parent div. 

Also, http://apps.testing.cwrc.ca/editor/dev/reader.htm#templates/ceww_new_entry_template lists the content of some other tags in the structure tab.

**Comment by ajmacdonald** [comment]
Ok. Can you please provide more detail on "If heading has no attribute, order and indent by the type of the parent div" ?

Re: the content of some other tags, I'm assuming you mean "{Standard name of the writer} ({Da…" ? If so, here is the XML for that heading:
```<HEADING SUBTYPE="2"><NAME STANDARD="">{Standard name of the writer}</NAME> ({Date of birth}-{Date of death})</HEADING>```
I'm not sure what else should be used in this case.

**Comment by ilovan** [comment]
To sum up:

CWRC schema: Use @level value
Orlando: use DIV0, DIV1, DIV2, etc
TEI: use the nesting structure of the DIV tags 

My bad, about the CEWW template - please ignore the previous note on that account.

**Comment by ajmacdonald** [comment]
I feel like the sorting/indenting should work for the schemas now. Please confirm and let me know of any irregularities.

**Comment by ilovan** [comment]
Thanks, Andrew, it seems to be working fine now. I am going to close it for now.
