### ISSUE TITLE
Upgrade to latest Tiny MCE

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#340]
Recommended in part b/c it will address some design issues, i.e. it is a flatter design.
Andrew estimates 10-12 hours for this. 
Susan says let's go ahead.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-Writer/commit/c07064c8374e48cb39896de612806d22513007b4

**Comment by susanirenebrown** [comment]
Great!
