### ISSUE TITLE
Entities don't have their attendant URIs (Annotator version)

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#345]
In the Annotator only version, the entities panel looks like this, and even if you double click on an entity you don't see the URI, thus:
![image](https://cloud.githubusercontent.com/assets/545952/8932339/87d6ce98-350a-11e5-965d-30ea6d9a6b74.png)
 As opposed to in the full version, where double clicking on an entity yields this kind of things:
![image](https://cloud.githubusercontent.com/assets/545952/8932364/af2b9c94-350a-11e5-984f-2c6ef16483e8.png)

**Comment by ajmacdonald** [comment]
I'm having trouble reproducing this.
