### ISSUE TITLE
Start administrative documentation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#347]
James kindly volunteered to start this. I suspect that it should either be a file in github or that @ilovan will want it done in DITA. We can debate that after her holidays. For not, though get a basic start in some easily transferable format.

**Comment by ilovan** [comment]
James, could you please update us on this issue? Thanks.

**Comment by jchartrand** [comment]
Thank you for the nudge - I’m on it now.  

And so, as we talked about during our last call, I’ve updated the GitHub README in the dev branch:

https://github.com/cwrc/CWRC-Writer/blob/development/README.md

with a preliminary version.  I’ll keep at it, but please let me know what you think.  In particular:

- is the CWRC image that I've included okay?
- is there licence text you’d like included on the page?

**Comment by jchartrand** [comment]
I've started the docs, so closing this issue.  I'll continue to add to the docs as we go.  Comments/suggestions very welcome.
