### ISSUE TITLE
Entities in Orlando documents don't have attendant URIs 

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#348]
Same as #345

**Comment by SusanBrown** [comment]
Testing on http://cwrc-dev-01.srv.ualberta.ca/dev/CWRC-Writer/index.htm it still isn't fixed. 

When I insert an entity into the test letter, and I look at the entities panel, I see the values for cert, type and ref, thus:

![image](https://cloud.githubusercontent.com/assets/545952/9187867/716e777a-3fa3-11e5-83fb-0a15b149b4a5.png)

When I insert an entity into the test Orlando biography, and I look at the entities panel, I see only the string that I tagged and nothing else, thus:
![image](https://cloud.githubusercontent.com/assets/545952/9187892/a9394f7c-3fa3-11e5-9df0-0a1e9e568cd8.png)

**Comment by ilovan** [comment]
Hi Susan, the location you tested at does not get automatically updated with Andrew's newest code (more about this tomorrow during our PM checkin).

Andrew's most recent dev work can be tested at http://apps.testing.cwrc.ca/editor/dev/index.htm.

**Comment by SusanBrown** [comment]
I was wondering if something like this was going on, since Andrew had said he couldn't replicate it. I've updated my bookmarks to this one: sorry for the confusion.
