### ISSUE TITLE
Make removing or hiding the "Open Document" button on the CWRC-Writer configurable

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#349]
From dgi:

We also have another request for Open Sky if possible for integrating the template work. Could that add a configuration option that would Remove or Hide the Open Document button in the CWRC-Writer?

**Comment by ajmacdonald** [comment]
See https://github.com/cwrc/CWRC-Writer/blob/development/src/reader.htm#L57 for an example of how to configure the buttons that are available.

**Comment by ilovan** [comment]
Latest feedback from dgi: 
Still needed: Addition of the capability to toggle the Open Document button of the CWRC-Writer on/off at
runtime. 

@ajmacdonald , could you please give this issue the highest priority and/or pinpoint them to any existing code they might have missed?

**Comment by ajmacdonald** [comment]
Use the function I added in referenced commit https://github.com/cwrc/CWRC-Writer/commit/77c1e6946781b6c71fc1e75196bfcbdaca5a7aea
to get a button by name. Then use hide or show.

For example:
```
writer.getButtonByName('loadbutton').hide()
```

**Comment by jchartrand** [comment]
Andrew added this last week.  He correctly referenced the commit in the GitHub issue, but I should have also emailed you about it too.  My fault.

Anyhow, Andrew has added:

writer.getButtonByName(buttonName)

So, DGI can now call:

writer.getButtonByName('loadbutton').hide()

james
