### ISSUE TITLE
editing entity: can't get back to LOD picklist

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#350]
You can only edit the associated tag.

TO BE DECIDED: should we reintroduce the tag names associated with the entities into the picklist so they are easier to find/handle? Right now a tag linked to an entity behaves different from the same tag when it isn't associated with an entity.

**Comment by ilovan** [comment]
Not sure what you mean here, @SusanBrown : should we reintroduce the tag names associated with the entities into the picklist so they are easier to find/handle? 

I think clicking on "edit entity" should return the user to the second step of the entity creation process (second after the user has selected the type of entity she wants to tag, i.e. the entity lookup form).

**Comment by SusanBrown** [comment]
agree with your second point. About the first I'm still not sure so perhaps leave and consult about this in testing (make a note perhaps to specifically ask some users to alter an existing entity an perhaps also a tag without an entity and see what they think)
