### ISSUE TITLE
Add variable/configuration option to suppress Header for Read-only CWRC-Writer

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#351]
Question from Digital Echidna,

Is it possible that we are able to pass variables into CWRC Writer?  If so, could we pass a variable in that would allow us to not show the header at all?  If this is the case, we could use CWRC Writer in read only mode on Project Homepages, to render fedora objects.  This would be great.

**Comment by ajmacdonald** [comment]
This is possible, however, I think it would be better for them to develop their own customized setup. There are already a few examples of this in the repository, e.g. https://github.com/cwrc/CWRC-Writer/blob/development/src/basic.htm is a very stripped down version with no header, few buttons, and no side panels.

**Comment by SusanBrown** [comment]
So it is possible to configure this in the setup of CWRC-Writer? @jchartrand if this is the case, and you've documented it, please resolve this issue.

**Comment by jchartrand** [comment]
Yes, there are examples showing how to customize the layout.  I've also split the layout into a separate NPM module to hopefully allow easier customization.
