### ISSUE TITLE
Make images displayable in CWRC Writer

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#352]
Is this possible?

If the image is saved in the repository and the image tag contains the image URI, could we have the image displayed in the text area at its location and styled according to instructions specified in the associated stylesheet?

**Comment by ajmacdonald** [comment]
It's possible.
We would need a way (in the schema?) to mark a specific tag as an image tag, so that I could replace it with the appropriate HTML tag.

**Comment by ilovan** [comment]
I know there are options for the TEI schema and that we have the Figure tag in the CWRC entry schema. I don't think we're going to need images inside Orlando documents, so no need of mapping there. 
@brundin , could you please provide the appropriate mappings for http://cwrc.ca/schemas/documentation/CWRC_entry/index.html#FIGURE and the other elements in its model, as well as the TEI image elements?

**Comment by brundin** [comment]
Will do.  -- MRB

**Comment by brundin** [comment]
Hi Andrew,

I have added the mappings for the TEI figure element and the CWRC entry
FIGURE element to the respective annotation object documents -- the
figure/FIGURE mappings appear at the bottom of both of these documents:

CWRC annotation object document:
https://docs.google.com/document/d/11WBJMToqzuwrDPa1XZ9l80Wo1uNERALGHM1Lxwy16mw/edit

TEI annotation object document:
https://docs.google.com/document/d/1swmwJdgqxyMmd6YIhq6nPuKA7Na5EadYG6xVk4ua3MY/edit

The sample code blocks that are provided in these documents look like this:

CWRC sample code block for the FIGURE element:

```

               <FIGURE>

                   <HEADING>Heading of image here</HEADING>

                   <FIGDESC>Description of the image here.</FIGDESC>

                   <GRAPHIC URL="http://cwrc.ca/path/to/image/here.jpg"/>

               </FIGURE>
```

TEI sample code block for the figure element:

```

       <figure>

           <head>Heading of image here</head>

           <figDesc>Description of the image here.</figDesc>

           <graphic url="http://cwrc.ca/path/to/image/here.jpg"></graphic>

       </figure>
```

Cheers,
Michael

**Comment by ajmacdonald** [comment]
So is this a new entity type then?
What about graphic tags that aren't inside figure tags?

**Comment by brundin** [comment]
No, it won't be a new entity type.  It's a just a way to mark up a figure
or graphic image.  The cwrc_entry.rng FIGURE element is modeled exactly the
same way as the TEI figure element -- see the TEI documentation for the
figure element here (note the example down at the bottom of the page):

http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-figure.html

In the TEI, the child graphic element can appear in other places than in
the figure element, such as the p element, so I have now made the CWRC
entry GRAPHIC element available in the CHRONPROSE, DATAITEM, and P
elements, in addition to the FIGURE element.  I also created a HEAD
element, so the old HEADING element in the FIGURE element is now the HEAD
element (this parallels the naming in the TEI figure element).

So, the upshot is that we can use the GRAPHIC element, with its URL
attribute, as a way to reference inline graphic information.

I believe this arose from a use case that emerged in the CEWW projects,
where they would like to reference a photograph of an author.  They can now
use the GRAPHIC element with its URL attribute to reference the appropriate
image.

**Comment by ilovan** [comment]
Michael is right about this not being a new entity. 

Going back to your initial question, Andrew: "We would need a way (in the schema?) to mark a specific tag as an image tag, so that I could replace it with the appropriate HTML tag"

The tag to mark as an image in both the CWRC entry schema and the CWRC TEI is GRAPHIC (graphic respectively), with the URL attribute.

**Comment by brundin** [comment]
Thanks for clarifying this, Mihaela (i.e., distilling it from my
long-winded discourse above!).

Michael

**Comment by ajmacdonald** [comment]
Should be working now. Please test and confirm.

**Comment by ilovan** [comment]
Tried both png and jpeg in a TEI document (http://apps.testing.cwrc.ca/editor/dev/editor_dev.htm#ImageTest) and in a CWRC entry document (http://apps.testing.cwrc.ca/editor/dev/editor_dev.htm#ImageTestTEI)
Do we need to modify the style sheet to render the images at all? If so, I'll also test in dev 05.

**Comment by ajmacdonald** [comment]
There's a race condition with the loading of files that I need to fix.
If you add a graphic tag from within the editor it should display the image from the URL.

**Comment by ajmacdonald** [comment]
Should be fixed now. The wikipedia hosted image in ImageTestTEI doesn't load because it's not a direct link to the image. The other image works fine for me.

**Comment by ilovan** [comment]
Tested in CWRC and TEI documents with .jpg and .png images. 
Also, at @SusanBrown 's request, @brundin is adding image support to the Orlando schemas as well. 

Michael, could you please let Andrew know when the edits to the Orlando schemas are complete and what elemets/attributes you used for images in those schemas?

**Comment by brundin** [comment]
Andrew/Mihaela: the edits to the Orlando schemas are complete with respect
to adding image support.  The elements/attributes for the Orlando schemas
are exactly the same as with the CWRC entry schema, i.e., the elements
GRAPHIC and FIGURE.

* orlando_biography.rng schema additions:
  - Created a new element GRAPHIC, with attribute URL, as a child element
to the elements CHRONPROSE, DATAITEM, P, and RESEARCHNOTE.
  - Created a new element FIGURE as a child element to the elements
CHRONPROSE, DATAITEM, P, and RESEARCHNOTE; FIGURE has a child element of
FIGDESC, and
    REFs to child elements of GRAPHIC, HEAD, and P.

* orlando_event.rng and orlando_writing.rng schema additions:
  - Created a new element GRAPHIC, with attribute URL, as a child element
to the elements CHRONPROSE, P, and RESEARCHNOTE.
  - Created a new element FIGURE as a child element to the elements
CHRONPROSE, P, and RESEARCHNOTE; FIGURE has a child element of FIGDESC, and
REFs to child
    elements of GRAPHIC, HEAD, and P.

The only difference among the 3 Orlando schemas is that the GRAPHIC and
FIGURE elements are also available in the DATAITEM element in the
orlando_biography.rng schema (the DATAITEM element is only available in the
orlando_biography.rng schema -- it's not in the orlando_event.rng and
orlando_writing.rng schemas).

MRB

**Comment by ilovan** [comment]
Thanks, @brundin . 

Andrew, can you please proceed to adding image support for the Orlando schemas in CWRC-Writer?

**Comment by ajmacdonald** [comment]
Done.
