### ISSUE TITLE
Does CWRC-Writer support foldout styling?

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#353]
My thought is that it didn't used to, but this may have changed with the updated TinyMC. 
If it hasn't, is there anyway we could make this work and how involved would it be?

**Comment by ajmacdonald** [comment]
@ilovan can you describe what foldout styling is?

**Comment by ilovan** [comment]
something like this or a bit nicer: 

http://yourshoesuntied.com/css-showing-and-hiding-content/

**Comment by ajmacdonald** [comment]
Yes this is possible. It would involve adding the appropriate styles to the CSS for each schema.

**Comment by ilovan** [comment]
Great, thanks. I will test this with a modified version of the CWRC Playwrights css and get back to you if I encounter any issues
