### ISSUE TITLE
Double clicking on a word can select more than one word

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#354]
In Orlando Sample Biography double clicking on the initial PJ under the Heading Birth and Circumstances also selects "1861" along with "PJ". Clicking on an entity button then brings up the overlapping tag message.

**Comment by ilovan** [comment]
Tested further: 
Could only reproduce the bug in Chrome (both read-only and editor), but not in Firefox.

**Comment by SusanBrown** [comment]
@cailinr see if you can reproduce this and if not close
