### ISSUE TITLE
Read only mode: selecting text allows you to alter doc text

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-Writer#355]
Selecting some text and then typing which alter the text.

**Comment by ilovan** [comment]
Not sure to what extent this is useful or not, but I tested this in both Chrome and Firefox; 

In Chrome, the selected string is replaced with the first letter/symbol typed (anything typed after does not register and the selection is canceled)

In Firefox, I could not reproduce the issue.
