### ISSUE TITLE
CWRC entry schema: orgtype attribute not available for ORGNAME

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#357]

**Comment by brundin** [comment]
The cwrc_entry.rng schema has the @ORGTYPE attribute enumerated list of
values in the ORGNAME element.  The @ORGTYPE attribute was not listed in
the "Annotation object forms -- CWRC entry elements and attributes"
document, so I added it in the "Organization" section:

https://docs.google.com/document/d/11WBJMToqzuwrDPa1XZ9l80Wo1uNERALGHM1Lxwy16mw/edit

MRB
