### ISSUE TITLE
Save and Exit icon and REST Endpoints

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#362]
Message from DGI:

Adding a “Save and Exit” icon and implementing a REST endpoint such that dgi can provide the back-end action that will save the document, release the lock, and return a URL that the CWRC-Writer client will then use to redirect the user to another page (to support Object Locking Module updates).

Comment from James:
Andrew estimates an hour or two to add a new delegator call that will be triggered by the button click.  He’ll redirect to the returned page in the callback.

**Comment by ajmacdonald** [comment]
I've added the basis for this. DGI needs to either give me more specifics, or alter the delegator call themselves.
Also, the new button is not included by default. It needs to be added using the ```config.buttons1``` property.
