### ISSUE TITLE
URLs to test notes behaviour in the read-only and annotation-only modes

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#366]
The URL you provided a while back for the read-only mode : http://apps.testing.cwrc.ca/editor/dev/reader.htm#templates/sample_biography seems to be down.

I would like to see how a note pop-up looks like in the two non-editing modes. (though users will not be able to edit the notes in this mode, they should still be able to see their content)

**Comment by ajmacdonald** [comment]
Read-only mode should work if you empty your cache.
There is currently no behaviour in place to view note content without editing it.

**Comment by ilovan** [comment]
Read-only mode does work now, thank you. 

Not being able to view the content of the notes in the read-only or annotate only mode is  not good. 

@SusanBrown , 
I am pulling you into this conversation. 
Please look at the note in http://apps.testing.cwrc.ca/editor/dev/reader.htm#testApril

The way I see it, 
It would be preferable if we could have a read-only, annotate only version of the mini-CWRC-Writer to pop up when someone clicks on the note icon in the text area. This would allow users to annotate (add rdf only) scholar notes for example.

If this is impossible or too much to change in the existing code, we could go with a much simpler pop-up for both non-editing modes, maybe something similar to the editor mode popup (XML only, XML & RDF, etc.) or even the settings pop-up.

What do people think?

**Comment by SusanBrown** [comment]
Thanks for pulling me in as I almost added an issue about this when I saw you discussing it earlier. I agree totally that we should make a read-only view of the notes a high priority. Please create a ticket.
