### ISSUE TITLE
Entity URIs - review code and behaviour.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#368]
CWRC entity lookup and creation doesn't work with the stand-alone version of the CWRC-Writer, but that in itself is not necessarily an issue since we made these configurable from within the dgi-built integration module.

I noticed, however, that in the integrated version of CWRC-Writer, the CWRC entity URIs listed in the entities tab and the ones users can see in the disambiguation ("info") bubble in the entity lookup dialog are prefixed by "null" instead of "http://commons.cwrc.ca/" as they should:

![image](https://cloud.githubusercontent.com/assets/6600070/14712490/91c76ed6-079a-11e6-900d-c49cfcbcb52e.png)

I suspect that this is more of an integration module issue, but before I contact dgi, could you please check that the problem is not something that crept in when you were making the dialogs easier to integrate with CWRC Writer or when you were updating the TinyMC?

Two starting points that we can think of: 

- issue #325 add setRepositoryBaseObjectURL to the initial config
- configuration file: https://github.com/cwrc/CWRC-Writer/blob/development/src/js/writerConfig.js

**Comment by ajmacdonald** [comment]
I'm seemingly unable to access the integrated version with my previous credentials. Can you email me new ones?

**Comment by ilovan** [comment]
Just did, let me know if you're still having issues.

**Comment by ajmacdonald** [comment]
You're correct, it is an integration issue. This property is missing from dgi's config: https://github.com/cwrc/CWRC-Writer/blob/development/src/js/writerConfig.js#L5

**Comment by jordandukart** [comment]
Hey @ilovan,

Should the `repositoryBaseObjectUrl` setting be set as the prefixed part of the URL or the fully resolvable path? For example, `http://commons.cwrc.ca/entitypid` vs `http://commons.cwrc.ca/islandora/object/entitypid`?

**Comment by ilovan** [comment]
Hi @jordandukart , 

We would like to go with http://commons.cwrc.ca/entitypid.

We also need to keep in mind that we are in process of adopting ssl on beta. 
Is this going to affect the behaviour when clicking on an http: link?
@ajmacdonald ,
if you could join this conversation, that would be great.

**Comment by ajmacdonald** [comment]
I'm not an expert but if you have SSL I think you need to specify https in the link in order to take advantage of it.

**Comment by ilovan** [comment]
we're still testing SSL, so for now, let's go with http://commons.cwrc.ca/entitypid.
