### ISSUE TITLE
Insert tag outside

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#378]
I think we asked for this some time ago. @ajmacdonald and @jchartrand is there any reason we can't do this (and ideally around a number of tags selected in the left panel) or has it just never risen to the top of the priority ilst?

**Comment by ajmacdonald** [comment]
This functionality used to exist but was removed here: https://github.com/cwrc/CWRC-Writer/commit/641593c26c6dfd0a20a405301b196c5956c1c72d#diff-e1a89b6ea7dd7b0ad95f42299549820eL365
Unfortunately I didn't make a note as to why.

It is easy to re-enable.

**Comment by SusanBrown** [comment]
Let’s try re-enabling it. Is there any way to permit selection of multiple tags within the tag panel and to allow for insertion of a tag around them? That would be much more useful than inserting around a single tag.

**Comment by ajmacdonald** [comment]
I'm starting to look into this.
In the case of selecting multiple tags, what do you expect to happen if: 1) the tags aren't siblings, 2) the tags are siblings but are not in a consecutive sequence?

**Comment by ilovan** [comment]
I believe that if the tags are not siblings (i.e. on the same level of the
XML hierarchy, sharing the same parent) or if they are not in consecutive
sequence, this option should not be available.

On Thu, May 26, 2016 at 4:00 PM, Andrew <notifications@github.com> wrote:

> I'm starting to look into this.
> In the case of selecting multiple tags, what do you expect to happen if:
> 1) the tags aren't siblings, 2) the tags are siblings but are not in a
> consecutive sequence?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/CWRC-Writer/issues/378#issuecomment-222007723>
>



-- 
Mihaela Ilovan

Project Manager
Canadian Writing Research Collaboratory
University of Alberta
4-20 Humanities Centre
Edmonton, AB
Canada T6G 2E5

780-492-7803
ilovan@ualberta.ca

**Comment by SusanBrown** [comment]
agree.

**Comment by SusanBrown** [comment]
Seems fixed.
