### ISSUE TITLE
Fix automatic scroll of the structure panel when different locations in the document have been clicked

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#379]
related to #338 
When you double-click on the tag in the body of the entry, the side bar will highlight the corresponding tag, but the highlighted bar remains below the screen. Hence, in the screenshot, you can't see the highlighted tag.
![screen shot 2016-05-10 at 11 57 54 am](https://cloud.githubusercontent.com/assets/6600070/15170953/d9a8cf2a-1707-11e6-84af-95fc442a714c.png)

**Comment by SusanBrown** [comment]
This seems much better but not entirely fixed. Seems to happen when you click a tag at the bottom of the screen

**Comment by ajmacdonald** [comment]
Please test

**Comment by SusanBrown** [comment]
Seems fixed
