### ISSUE TITLE
Inconsistent behaviour: VIAF "i"button

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#380]
Clicking on the URL that opens when the "i" button in VIAF lookup is pressed makes the browser want to leave the page instead of just automatically opening up a new tab.

![screen shot 2016-05-10 at 1 06 14 pm](https://cloud.githubusercontent.com/assets/6600070/15171004/528b95c6-1708-11e6-8ff7-b167ce1e3da2.png)

**Comment by SusanBrown** [comment]
Seems to be resolved in both versions.
