### ISSUE TITLE
validator down for stand-alone CWRC-Writer

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#381]
Andrew, can you please consider this a high priority (I'll come up with a list of priorities for next week once I have completed my review of the existing tickets).

![image](https://cloud.githubusercontent.com/assets/6600070/15261349/298782a8-1919-11e6-9ee7-b4a25578b0d4.png)

**Comment by jefferya** [comment]
There server hosting the cwrc validator for the standalone version of
CWRC-Writer is down. How urgent is this?

**Comment by ilovan** [comment]
If it's not affecting anything else, I can do without until Monday.

**Comment by jefferya** [comment]
Server is once again functioning.

**Comment by ilovan** [comment]
Great,

Thanks, Jeff.

I am going to close this now.


On Mon, May 16, 2016 at 9:48 AM, Jeffery Antoniuk <notifications@github.com>
wrote:

> Server is once again functioning.
>
> On Fri, May 13, 2016 at 4:13 PM, Mihaela Ilovan <notifications@github.com>
> wrote:
>
> > If it's not affecting anything else, I can do without until Monday.
> >
> > Sent from a mobile device
> >
> >
> > > On May 13, 2016, at 17:54, Jeffery Antoniuk <notifications@github.com>
> > wrote:
> > >
> > > There server hosting the cwrc validator for the standalone version of
> > > CWRC-Writer is down. How urgent is this?
> > >
> > > On Fri, May 13, 2016 at 2:46 PM, Mihaela Ilovan <
> > notifications@github.com>
> > > wrote:
> > >
> > > > Andrew, can you please consider this a high priority (I'll come up
> > with a
> > > > list of priorities for next week once I have completed my review of
> the
> > > > existing tickets).
> > > >
> > > > [image: image]
> > > > <
> >
> https://cloud.githubusercontent.com/assets/6600070/15261349/298782a8-1919-11e6-9ee7-b4a25578b0d4.png
> > >
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/cwrc/CWRC-Writer/issues/381>
> > > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cwrc/CWRC-Writer/issues/381#issuecomment-219172218>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cwrc/CWRC-Writer/issues/381#issuecomment-219461425>
>



-- 
Mihaela Ilovan

Project Manager
Canadian Writing Research Collaboratory
University of Alberta
4-20 Humanities Centre
Edmonton, AB
Canada T6G 2E5

780-492-7803
ilovan@ualberta.ca

**Comment by ilovan** [comment]
Closed, with a caveat from Jeff that it may happen again and that he should be notified immediately if it does.
