### ISSUE TITLE
Merge two identical consecutive tags.

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#383]
Allow users to join consecutive identical tags  (e.g. p, divs, etc.) if they select both of them in the structure panel. 

@SusanBrown , you also proposed that joining tags should be an option if the cursor is positioned at the start of the second identical tag in the text area. It seems to me that this would make accidentally merging tags easier, so I would suggest we stay with the structure panel option only. What do you think?

**Comment by susanirenebrown** [comment]
Sounds fine with me to do it as you suggest.

**Comment by SusanBrown** [comment]
Works!
