### ISSUE TITLE
In the embedded CWRC-Writer, I can't find the Edit Source option when I am viewing the source. 

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#394]
Has it moved or disappeared?

**Comment by ajmacdonald** [comment]
I don't think it ever existed in that panel.

**Comment by SusanBrown** [comment]
where is it?

**Comment by jchartrand** [comment]
In the standalone CWRC-Writer the edit source button is right beside the view source button in the main toolbar.

**Comment by SusanBrown** [comment]
Not sure what was going on but it's definitely there now!
