### ISSUE TITLE
Add to the standalone version of CWRC-Writer the template for Orlando templates

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#396]
Please add the template at http://cwrc.ca/templates/orlando_event_CWRC-Writer_template.xml, with the associated schema and css style.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-Writer-Templates/commit/ce2ee0aa790c84a7edcf984d2cc8e3e5bbd62bb6
