### ISSUE TITLE
insertion of new paragraph by enter key is not shown in tag panel.

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#399]
Using the Enter key creates a new paragraph, as it ought. However, the left panel does not show the new tag.

Integrated CWRC-Writer
Browser: Chrome

**Comment by ajmacdonald** [comment]
Sometimes works, sometimes doesn't. Will need to narrow down the conditions.

**Comment by SusanBrown** [comment]
Needs further work.

**Comment by ajmacdonald** [comment]
Could be related 41f7649622e84ee70a20eac02edf32663f44ef8d

**Comment by ilovan** [comment]
tested in GitWriter as well, using all supported schemas. it worked consistently, so I am closing this issue for now.
