### ISSUE TITLE
In standalone CWRC-Writer, inserting a note tag prompts keyword popup

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#404]
Standalone CWRC-Writer, dev version

![image](https://cloud.githubusercontent.com/assets/545952/17127722/c8109752-52d5-11e6-9643-b1eeaec400b0.png)

**Comment by ajmacdonald** [comment]
I'm having trouble duplicating this. Can you specify the document or schema you're using?

**Comment by susanirenebrown** [comment]
I believe it was the Sample Letter file from the standalone CWRC-Writer menu.

**Comment by ajmacdonald** [comment]
Since keyword, note, and citation can have the same parent tag in TEI, I could see how it might be possible for this to occur. However, I still can't reproduce it so I can't determine what needs fixing.

**Comment by SusanBrown** [comment]
Can't replicate. Closing for now.
