### ISSUE TITLE
In the embedded CWRC-Writer, the notification of what mode you are in pushes the window down

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#407]
It should appear right at the top of the window, just below the buttons. The way it works now you have to scroll back up to the top of the page.

![image](https://cloud.githubusercontent.com/assets/545952/17249443/fa39f062-556d-11e6-9baa-18fd66fb5130.png)

**Comment by SusanBrown** [comment]
@ajmacdonald Could you please, when you look at this, indicate whether the general popup window problems can be dealt with within CWRC-Writer? It would be preferable, I think, if we could anchor the popups more towards the top of the screen, because that is often a problem on laptops with small screens. However, let us know if it needs to be dealt with by Digital Echidna.

I've rearranged this on the priority list to give these items precedence after the hyperlinking problem, since we need to firm up scoping for the next round of work from Digital Echidna.

**Comment by ajmacdonald** [comment]
I've tried to reproduce this problem in the non-embedded version but have been unable. It's likely a CSS conflict but I'm having difficulty determining where.

What's happening in the embedded version is that the dialog's title bar height is being calculated as much larger than it should be. This is forcing the dialog down the page.

![screenshot](https://cloud.githubusercontent.com/assets/882444/17379965/b6ab272a-5992-11e6-91f5-a76f3ef52740.png)

**Comment by SusanBrown** [comment]
Ok, I will inquire of Echidna then whether this can be changed.

On Aug 3, 2016, at 3:55 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


I've tried to reproduce this problem in the non-embedded version but have been unable. It's likely a CSS conflict but I'm having difficulty determining where.

What's happening in the embedded version is that the dialog's title bar height is being calculated as much larger than it should be. This is forcing the dialog down the page.

[screenshot]<https://cloud.githubusercontent.com/assets/882444/17379965/b6ab272a-5992-11e6-91f5-a76f3ef52740.png>

**Comment by SusanBrown** [comment]
Digital Echidna working on this

**Comment by ajmacdonald** [comment]
Should be fixed: https://github.com/cwrc/CWRC-Writer/commit/dcd6dd7fc9120b3ecef0c8fc114ccf136053ae7a
Please test.

**Comment by SusanBrown** [comment]
Yes, fixed!  THANK YOU!
