### ISSUE TITLE
Validation help popup placement -- embedded version

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#410]
Appears way below the CWRC-writer panel. Is this something you can address, Andrew?
![image](https://cloud.githubusercontent.com/assets/545952/17255779/ad1f4a5a-5588-11e6-8683-a5d8508645d1.png)

**Comment by ajmacdonald** [comment]
This appears to be a duplicate of / related to #407

**Comment by SusanBrown** [comment]
Digital Echidna working on this

**Comment by SusanBrown** [comment]
Fixed
