### ISSUE TITLE
Edit source box also appears below cwrc-writer panel in embedded version

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#412]
![image](https://cloud.githubusercontent.com/assets/545952/17256240/b0caa4f4-558a-11e6-82b1-56a41ab3eaad.png)

**Comment by ajmacdonald** [comment]
Duplicate / related to #407

**Comment by SusanBrown** [comment]
Digital Echidna working on this

**Comment by SusanBrown** [comment]
Fixed
