### ISSUE TITLE
default expansion of CWRC-reader structure panel 

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#414]
Is this something you can control, Andrew? We want the structure panel to be expanded by default.

**Comment by SusanBrown** [comment]
I see this is a duplicate of #393 which was closed. However items loaded into the embeded CWRC-Writer still have the panel closed by default:

http://cwrc-dev-06.srv.ualberta.ca/islandora/object/cwrc%3Ab36c5553-5b33-4735-93ae-6f9754740b11#cwrc:b36c5553-5b33-4735-93ae-6f9754740b11

**Comment by SusanBrown** [comment]
Hi @ajmacdonald Just moved this up in priorities list. Want to know if this is something in your control or whether I need to flag it for Echidna.

**Comment by ajmacdonald** [comment]
This is something they'll have to update in their files.
It's something that occurs in the "layout" file, which is specific to each implementation of CWRC-Writer.

**Comment by SusanBrown** [comment]
OK great. Can you please provide exact syntax/details?

On Aug 4, 2016, at 2:50 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


This is something they'll have to update in their files.
It's something that occurs in the "layout" file, which is specific to each implementation of CWRC-Writer.

**Comment by ajmacdonald** [comment]
You have to call ```w.layout.open(REGION_NAME)```.
Here is where I made the change for the standalone version: https://github.com/cwrc/CWRC-Writer/commit/d91dacbef76e4e50448e0c6d7271249638460f0c
Where they add this will be different for them because they don't have the button/link to switch between Reader and Editor modes.

**Comment by jefferya** [comment]
I know how to accomplish, I'm uncertain which islandora_cwrc_writer githup
repo to use.

js/islandora_cwrc_writer.js
line 327
writer.layout.open('west');

**Comment by susanirenebrown** [comment]
How many are there? Change them all??? *Can* you change them all?

**Comment by jefferya** [comment]
DGi, Echidna, and me. I'll try to figure out things.

**Comment by jefferya** [comment]
@SusanBrown Needs testing in the integrated environment. Also, some sorting out of the islandora_cwrc_writer GitHub.

**Comment by SusanBrown** [comment]
Working well in integrated environment. 

has the github been sorted out? If so this card can be closed.

**Comment by jefferya** [comment]
I'm hoping this is being sorted out as part of the github work Echidna is
currently work upon.

**Comment by susanirenebrown** [comment]
That is what I was hoping!
