### ISSUE TITLE
Could we call the CWRC-Writer in read-only mode CWRC-Reader along the top bar, and change it to CWRC-Writer when it's in editing mode?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#415]
How involved would this be, Andrew?

**Comment by ajmacdonald** [comment]
Simple.

**Comment by SusanBrown** [comment]
:)
On Aug 4, 2016, at 6:24 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


Simple.
