### ISSUE TITLE
Notes not being inserted in standalone cwrcwriter

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#421]
You can apparently create a new note (unlike in the embedded version, you see the tag hierarchy in the structure panel, and you can type and save, and a note icon appears in the text after the text you selected), but nothing happens when you click on the note icon, and no markup is inserted in the XML judging from the Edit Source view.

**Comment by ajmacdonald** [comment]
Please test.

**Comment by SusanBrown** [comment]
Tested. Works fine in standalone
