### ISSUE TITLE
Clicking on a Validation error item in the standalone CWRC-Writer doesn't scroll to and highlight the error in the editing panel

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#425]

**Comment by ajmacdonald** [comment]
Can't reproduce easily.

**Comment by SusanBrown** [comment]
@colinraybrian Could you please test this too (I think you were encountering it the other day), first in the standalone version, and if not found then in Dev05 and if not found then the standalonen (http://apps.testing.cwrc.ca/editor/dev/index.htm) ?
