### ISSUE TITLE
Resp attributes in orlando schemas not showing up in CWRC-Writer

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#428]
@jefferya noticed that the CWRC-Writer is not properly loading the values specified in the Orlando schemas for the RESP attribute on the CHRONSTRUCT element.
I verified this in the Sample Biography Document in the standalone CWRC-Writer, by inserting a new chronstruct element after the Heading that reads Grandfather.
![orlando_cronstuct_resp_object](https://cloud.githubusercontent.com/assets/545952/17409462/6759c14e-5a3d-11e6-8d09-ef67ba55a9f8.jpg)

**Comment by ajmacdonald** [comment]
Please test.

**Comment by SusanBrown** [comment]
Fixed.
