### ISSUE TITLE
After I convert a tag to an entity (NAME), I cannot access any attributes other then STANDARD through the entity popup

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#433]
Embedded CWRC-Writer
Orlando biography schema
Editing "Grant Allen" in Agnes Maule Machar: http://beta.cwrc.ca/islandora/object/islandora%3A1a806fe6-f1e4-45ae-bcca-fe03ae4ee2d1/edit-cwrc#islandora:1a806fe6-f1e4-45ae-bcca-fe03ae4ee2d1

There is no access to the REF attribute, for instance.

**Comment by ajmacdonald** [comment]
In all cases, REF is taken care of through the entity lookup.
Should it be available in the entity dialogs?

**Comment by SusanBrown** [comment]
Right, and I suppose the same is true of annotationID.

I think there might be cases where someone can’t get to the REF attribute through the lookups because it is sometimes really hard to get the right person, or already knows what it should be, or wants to use something from a LOD store not supported by the dialogs and so needs to put it in manually.


On Aug 24, 2016, at 12:12 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


In all cases, REF is taken care of through the entity lookup.
Should it be available in the entity dialogs?

**Comment by ajmacdonald** [comment]
Should the entity dialogs all have the "markup options" dropdown like in the TEI person entity dialog? This would include the ref/REF attribute.

**Comment by susanirenebrown** [comment]
Yes, I think that would be simplest. So the selected URI would go in the REF field/element but the use could input a URI manually if they so chose.

**Comment by ajmacdonald** [comment]
b2f92e85bca996018afcb58f96303721722cbb9e

**Comment by ajmacdonald** [comment]
I've now added it to all the entities except for the note-type ones.
