### ISSUE TITLE
CSS problem with chronstruct tags in CWRC-Writer

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#440]
@ajmacdonald this is another stylesheet problem that we could really use some help with.

[Standalone and embedded versions]

CHRONSTRUCT tags in Orlando schemas contain information about events.

With the stylesheet in the publication environment, they get rendered like this:
![image](https://cloud.githubusercontent.com/assets/545952/18494524/8e03ea42-79e4-11e6-8304-ed61271fafe8.png)

As CWRC-Writer interprets the stylesheet, they don't get rendered at all, as in the example below which is from the sample biography doc in the standalong cwrc-writer
http://apps.testing.cwrc.ca/editor/dev/editor_dev.htm#templates/sample_biography:

![image](https://cloud.githubusercontent.com/assets/545952/18494439/2619fdd6-79e4-11e6-93bb-637e2fbdbd95.png)

We can do without the icons altogether if they are the problem, though it would be nice to keep them. Can you please tell us how we can fix the CSS code so that they are visible, ideally laid out somewhat along the lines shown at the top here?

**Comment by ajmacdonald** [comment]
Add a "before" pseudo-element
```
CHRONSTRUCT[CHRONCOLUMN = "WRITINGCLIMATE"]::before {
    content : url(http://cwrc.ca/templates/images/book1.gif);
}
```

**Comment by SusanBrown** [comment]
@jefferya Can you make the change to the stylesheet, or shall we ask Abi to do it?

**Comment by SusanBrown** [comment]
They **are** showing up in the embedded version; standalone stylesheet just seems out of sync. Probably not worth trying to fix since we'll soon hope to shift to the github version for a sandbox.

**Comment by jefferya** [comment]
@SusanBrown 

Completed, I think (but untested), in the CSS used by the embedded version of CWRC-Writer (orlando_v2_cwrc-writer.css) but the standalone may use a different CSS.

https://github.com/cwrc/CWRC-Schema/commit/fb35a47f06705b1bb68bf69b24c663de8ab19970#diff-f0321d341584cca0621588614aeca72b
