### ISSUE TITLE
popup re: CWRC-Writer settings is sometimes empty

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#445]
I think it has been empty when I have loaded a doc in view mode previously, and it has just done it again when I saved and exited, applied workflow stamp, and the editor switched to view/CWRC-reader mode.

![image](https://cloud.githubusercontent.com/assets/545952/19011113/f9be02f8-875a-11e6-8643-3a03a7123073.png)

Doc: http://beta.cwrc.ca/islandora/object/islandora:1a806fe6-f1e4-45ae-bcca-fe03ae4ee2d1?lid=207576#islandora:1a806fe6-f1e4-45ae-bcca-fe03ae4ee2d1

**Comment by ajmacdonald** [comment]
This has been fixed by: https://github.com/cwrc/CWRC-Writer/commit/e2d443496811c0dfbd0be47d74df61befb63e07f
