### ISSUE TITLE
Images not rendering in either standalone or embedded CWRC-Writer

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#447]
@ajmacdonald or @jefferya Any idea why the images of playwrights which were working fine until recently would have stopped showing?

The doc:
http://beta.cwrc.ca/islandora/object/cwrc%3A48d32cac-d571-47be-bbda-91a9f6c9a3b8/edit-cwrc#cwrc:48d32cac-d571-47be-bbda-91a9f6c9a3b8

The code in the doc:
` <AUTHORSUMMARY><P><FIGURE><GRAPHIC URL="http://beta.cwrc.ca/islandora/object/cwrc%3Aecb0fe87-de36-4d73-9bb4-ef2eb106f92b/datastream/MEDIUM_SIZE/view"></GRAPHIC></FIGURE></P></AUTHORSUMMARY>`

I copied and pasted the raw XML from the embedded version and pasted it into the standalone to see if the image would render there. It didn't.

**Comment by jefferya** [comment]
@SusanBrown My gut feeling this is CSS related but since I was not in the original implementation I'm very much in the dark.  @ajmacdonald any thoughts?

**Comment by SusanBrown** [comment]
@jefferya Did you change the CSS when updating the schema objects? I don't believe it will have been modified recently other than that.

**Comment by jefferya** [comment]
@SusanBrown For the playwrights project unfortunately no changes were made on my end. There appear to be 3 different playwrights CSS files. for the one being referenced by the schema object, GitHub shows multiple changes in July and prior. Is this considered recent or did the problem start occurring afterwards?  I've scanned previous versions of the CSS and I'm unable to glean anything useful (i.e., my CSS assumption might be wrong). @SusanBrown Are there more details available such as who implemented the feature (e.g., Andrew or someone else)? When it was implemented?

**Comment by ajmacdonald** [comment]
This was caused by: https://github.com/cwrc/CWRC-Writer/commit/0953b03dbf527d992c950028217abd79f64cf439
I'll fix it.

**Comment by SusanBrown** [comment]
Hurray!  @jefferya can you pull this version into beta please, when you get a chance, and let me know?

**Comment by jefferya** [comment]
@SusanBrown  the  fix is now deployed on GitHub -
https://github.com/cwrc/CWRC-Writer/commit/0953b03dbf527d992c950028217abd79f64cf439

Note: one may have to clear their browser cache.
