### ISSUE TITLE
islandora_style.css - remove emic-logo reference?

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Writer#450]
A minor tweak to a CSS to remove a 404 not found error in the embedded CWRC-Writer. Can the reference to the emic-logo be removed? Here is the line:

https://github.com/cwrc/CWRC-Writer/blob/master/src/css/islandora_style.css#L95

Further question:
(1) Not certain if this CSS file should be part of the CWRC-Writer library?  Would it be better included within the Drupal module?  A better question, is it even needed?

**Comment by ajmacdonald** [comment]
It really shouldn't be part of the library as it is a custom styling of CWRC-Writer.

**Comment by SusanBrown** [comment]
Yes, please remove it if you haven’t already.

On Oct 4, 2016, at 3:03 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


It really shouldn't be part of the library as it is a custom styling of CWRC-Writer.
