### ISSUE TITLE
clarification in porting recent change into embedded version

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Writer#451]
@SusanBrown @ajmacdonald 

The following CWRC-Writer commit breaks the embedded version and I've a clarification question for @ajmacdonald because of my limited JavaScript experience. The commit for reference: https://github.com/cwrc/CWRC-Writer/commit/c6c660bdba21c071098e76e3992e8a50a6658d39

The module to embed CWRC-Writer overloads the formerly present filemanager.showLoader but this has been changed by the above commit. If I understand the changes, this line is no longer needed so I've removed it from the integration module: (https://github.com/jefferya/islandora_cwrc_writer/commit/58ed10b4e25906cff75e12778a0706026d25d815) 

Question, the integration module disables the 'load' button that allows the user to choose a doc or template from within the CWRC-Writer interface and if we are not using the 'load" button then we don't need to override the associated functions, correct? In other words, this file in the embedded version is no longer relevant: https://github.com/jefferya/islandora_cwrc_writer/blob/7.x/js/dialogs/fileManager.js

Thank you in advance.

**Comment by ajmacdonald** [comment]
Hi Jeff,
I changed the file manager dialogs to be consistent with the way the other dialogs worked.
Here's the current way to call them: https://github.com/cwrc/CWRC-Writer/commit/d21f570f1197915913f1cf7668686cc26ae7b11a
Unfortunately that prevents you from overriding the functions.

If you don't need the save and load dialogs then you won't need to override these functions.
