### ISSUE TITLE
Character entity references for angle brackets corrupting file for validation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#458]
This problem occurs in both the embedded versions, i.e. both with and without DE theming. Seems to be a bug that occurs because of the presence of the entity character references for angle brackets that occur in a revised template.

The line in the template that seems to be causing the problems:
`&lt;culturalformation&gt;&lt;religion&gt;&lt;div2&gt;&lt;shortprose&gt;&lt;p&gt;[prose description of sect or personal beliefs here]&lt;/&gt;&lt;/&gt;&lt;/&gt;&lt;/&gt;,&lt;/&gt;.`

The attempt is to render something like this:
`<culturalformation><religion><div2><shortprose><p>[prose description of sect or personal beliefs here]</></></></>,</>`

The result is that the XML seems to get corrupted so that it is missing some structural elements before being sent to the validation service and the CWRC-Writer says the file is invalid. The file validates without problem in Oxygen.

Here's the file in the unthemed embedded CWRC-Writer:
http://cwrc-dev-05.srv.ualberta.ca/islandora/object/cwrc%3A8a44b9cc-a695-40f3-a759-0a78d67c2c6b/edit-cwrc#cwrc:8a44b9cc-a695-40f3-a759-0a78d67c2c6b

Here's a screenshot from @jefferya showing the missing text:

![cwrc-writer_validate_cwrc 3abaeefd41-2b88-44d0-81cc-b73a96adcf57](https://cloud.githubusercontent.com/assets/545952/20433599/5a7b8164-ad72-11e6-9a60-16696d30300a.jpg)

**Comment by ajmacdonald** [comment]
Please test

**Comment by SusanBrown** [comment]
It validates in Dev05. Hurray! thanks for the quick fix!


On Nov 18, 2016, at 12:31 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


Please test
