### ISSUE TITLE
Odd selection error

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#459]
Document: http://beta.cwrc.ca/islandora/object/cwrc%3Ab7c47223-53ea-4f00-8c0b-65604c5d034b/edit-cwrc#cwrc:b7c47223-53ea-4f00-8c0b-65604c5d034b
Chrome on a Mac; embedded CWRC-Writer, but I loaded the doc into the standalone and replicated the error

Double clicked on word within tag to select it, but the word next to it but outside of the tag selected too. I can't get my cursor between the end of the tag and the "c" in "came" to insert a space, and I get the overlap error when I try to insert a tag around the selected tag, even when I select it in the Structure panel.

The document is valid and seems fine in Oxygen.
This is what the bit of text in question looks like:
`The day I was nine years old ,<persName corresp="#Rupert">Rupert</persName>came into the nursery `

![image](https://cloud.githubusercontent.com/assets/545952/20645008/c5dfe860-b41a-11e6-8d89-d274528de0bb.png)

![image](https://cloud.githubusercontent.com/assets/545952/20645011/d6d7d772-b41a-11e6-9322-e1654240d9f6.png)

**Comment by SusanBrown** [comment]
This may have to do with the processing of the Project Gutenberg texts via Gutentag as I see the same error in other docs. We have to reprocess these collections anyway to get rid of the spaces.

**Comment by ajmacdonald** [comment]
This has to do with how Chrome (and other browsers) select text and I can't think of how I could "fix" this.
