### ISSUE TITLE
Show entity label, not the string that is tagged, in entity panel

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#465]
Where it says "B" instead show "Bertrand Russell" or (since it comes from VIAF) "Russell, Bertrand, 1872-1970"

![image](https://cloud.githubusercontent.com/assets/545952/20645474/894922be-b42d-11e6-9a09-b968ba297d6b.png)

**Comment by ajmacdonald** [comment]
Done, although the year isn't included in the name info that comes back from the CWRC dialogs, so I can't display that.

**Comment by SusanBrown** [comment]
Great!
