### ISSUE TITLE
Standalone CWRC-Writer to use same Orlando CSS as embedded version.

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Writer#467]
Can the Standalone CWRC-Writer be set to use the same CSS as the embedded version for the Orlando documents (biography,writing,and events)? Here is the new CSS

http://cwrc.ca/templates/css/orlando_v2_cwrc-writer.css

Is this as simple as changing the writerConfig.js:

https://github.com/cwrc/CWRC-Writer/blob/development/src/js/writerConfig.js#L38

**Comment by ajmacdonald** [comment]
629eaf263cf91f5683f07ee369796b387d1f6417

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-Writer-Templates/commit/629eaf263cf91f5683f07ee369796b387d1f6417
