### ISSUE TITLE
If a CSS has a background colour, have that apply to the left panels as well.

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#475]
This will make for greater consistency of look and feel. 

See: http://beta.cwrc.ca/islandora/object/cwrc%3Aaa1d232a-34d2-4ffd-98b3-7f780bfcf338#cwrc:aa1d232a-34d2-4ffd-98b3-7f780bfcf338

**Comment by ilovan** [comment]
Moved here: https://github.com/cwrc/CWRC-WriterBase/issues/22
