### ISSUE TITLE
Blocked issue label

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#483]
Hi everyone, please use the new Blocked label for anything on which you are blocked pending a response from someone else after a reasonable period of time, so that we can easily locate these issues. @jchartrand @ajmacdonald @ilovan

**Comment by jchartrand** [comment]
Perfect!  I was actually just now also adding a blockers column to a new CWRC-Writer project that I just created:

https://github.com/orgs/cwrc/projects/4?

**Comment by susanirenebrown** [comment]
So does that make us great minds or fools? (hopefully the reference is not too obscure)

**Comment by jchartrand** [comment]
One interpretation of the 'fools seldom differ' bit seems to be that fools never argue or disagree.  So perhaps we’re in the clear there.

**Comment by jchartrand** [comment]
I also just used a BLOCKING label on this issue:

https://github.com/cwrc/CWRC-PublicEntityDialogs/issues/4

I’m adding some of these issues just to get some form of them, however inaccurate, into the system so we can refine them.  Please modify them freely, and move them around in the CWRC-Writer Project (or into other projects):

https://github.com/orgs/cwrc/projects/4?
