### ISSUE TITLE
Converting tags to entities on ingestion

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#484]
For when a document has been edited outside of CWRC-Writer.

When a document is opened in CWRC-Writer, have CWRC-Writer check whether all of the entities associated with RDF annotations that have contents in the ref attributes that would contain LOD URIs have such annotations. 

If a document has annotations with ref attributes and no corresponding RDF annotation, prompt the user with the question: "_Do you want to create semantic web (RDF) annotations based on the tags in this document?_" Possible answers:  _Yes | No | I need more information_
No: do nothing and close dialog box
Yes: create new entities and provide confirmation message: 
_"Created: 
3 name annotations
4 place annotations
2 link annotations."_
I need more information: Link out (new page) to documentation section on Named Entity Annotation. http://cwrc.ca/CWRC-Writer_Documentation/#Concept_Named_Entity_Annotation.html
[This section and the documentation generally need revision for better introduction of the concepts of the semantic web and annotation, but this will do for now.]

**Comment by ilovan** [comment]
Moved here: https://github.com/cwrc/CWRC-WriterBase/issues/new
