### ISSUE TITLE
Make XML  comments visible in CWRC Writer

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#486]
current behaviour: CWRC-Writer stripps away XML comments. 
desired behaviour: we would like to make comments visible in the editor view .

**Comment by ajmacdonald** [comment]
Suggested CSS rules for XML comments:
```
#comment {
	color: #ccc;
	display: block;
	margin: 0.5em;
}
```

**Comment by susanirenebrown** [comment]
So are they just invisible, not stripped??

**Comment by ajmacdonald** [comment]
@susanirenebrown they were stripped before. They will be visible now with or without that CSS.

**Comment by susanirenebrown** [comment]
OK, that is great. And it was really super to have the cert attribute definitions fixed for the demo we did today.
