### ISSUE TITLE
Figure out how to point to CWRC for authorization

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#492]
Not sure what the approach would be here, but obviously do now want people to be authorizing James so much as CWRC as a project. Should we create a cwrc_project github account, @jchartrand and if so can we reassign things so this doesn't point to you personally?

![image](https://user-images.githubusercontent.com/545952/34284899-4dd98a1c-e6a3-11e7-81ef-94162fc4d78c.png)

**Comment by SusanBrown** [comment]
@jchartrand Just added this to the priorities on deck.

**Comment by jchartrand** [comment]
I'll switch it over to the CWRC Github account.

**Comment by jchartrand** [comment]
Done.
