### ISSUE TITLE
Sample Cdn Women Playwrights entry CSS association broken?

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Writer#496]
Although I have been able to load some files with which I had the CSS problem successfully with the CSS, this one I couldn't get to work at all.

@ajmacdonald could you investigate what the problem would be? In the meantime, can we please remove it from the available templates?

**Comment by jchartrand** [comment]
Do you have this problem on the Production version:

http://208.75.74.217

or the development version:

http://208.75.74.225

I ask because I think the problem is with https, which is in place on the dev version, but not with the prod version.

We should now specify the version (prod, dev, or both) when reporting bugs.

**Comment by SusanBrown** [comment]
I do indeed get the error shown below when I go to the dev version.

But I get this error on the prod version too. CSS for other files are loading fine, just not this one. I tested them all. 

![image](https://user-images.githubusercontent.com/545952/34319786-3e94a1a2-e7b8-11e7-9f19-10ea4740671f.png)

**Comment by ajmacdonald** [comment]
The problem is that the file doesn't exist on the server at https://cwrc.ca/templates/css/playwrights.css
Others do exist, e.g. https://cwrc.ca/templates/css/tei.css

**Comment by SusanBrown** [comment]
Thanks, Andrew. @ilovan could you please rectify this?

**Comment by ilovan** [comment]
Hm, 
This has to do with [this commit](https://github.com/cwrc/CWRC-Schema/commit/84aab53afd2cfb7eb9f9d7974c5f7f75c44f19b9) from Jeff (I believe he took this decision about the project-specific stylesheets when ceww was frequently modifying theirs. 

I would hesitate to roll it back; could you @ajmacdonald change the URL to http://cwrc.ca/templates/css/obsolete/playwrights.css?

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-Writer-Templates/commit/bb26240e1244b77a49ab59b6ba14f0a7e8309222
