### ISSUE TITLE
text out of sync with parenthetical entity markers

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-Writer#80]
After I saved and reloaded a version of the Russell letter, the representation of the entity was out of sync with the text with which it was associated. Reloading the page didn't fix it. Using Chrome on a Mac. The info in the entity menu looked the same as always.

![image](https://f.cloud.github.com/assets/545952/1015962/39dd33ec-0bec-11e3-9b8f-770807febc5d.png)

Original: https://github.com/jchartrand/CWRCEditor/issues/71

**Comment by ilovan** [comment]
I couldn't reproduce this and never encountered it in recent times. It may have been connected to a certain (past) version of the browser.
